[build-system]
#requires = ["setuptools>=42", "wheel"]
requires = ["maturin>=1.4,<2.0"]

#build-backend = "setuptools.build_meta"
build-backend = "maturin"

[tool.maturin]
features = ["pyo3/extension-module"]

[tool.pytest.ini_options]
markers = [
	"mongodb: marks mongodb tests"
]