exclude = [
    ".venv",
	"build",
    ".git",
]
select = [
    "ALL"
]
ignore = [
    "C901", "N818", "N805", "D1", "D2", "D400", "D415", "D401", "YTT", "ANN", "S", "B", "C4", "DTZ", "EM", "EXE",
    "FA", "INP", "PYI024", "PT", "RET503", "RET505", "ARG", "PTH123", "TD", "FIX", "PL", "RUF013", "TRY003", "TRY200"
]

line-length = 120
target-version = "py310"
[flake8-quotes]
inline-quotes = "single"

[per-file-ignores]
"panther/main.py" = ["F405", "F403"]
"panther/app.py" = ["SIM102"]
"panther/utils.py" = ["UP004", "UP008"]
"panther/cli/run_command.py" = ["PTH109"]
"panther/cli/*" = ["T201"]
"panther/db/models.py" = ["A003", "SIM108"]
"panther/db/queries/queries.py" = ["SIM108"]
"panther/routings.py" = ["SIM108"]
"panther/status.py" = ["PLR2004"]
"panther/_utils.py" = ["ERA001"]
"example/app/apis.py" = ["ERA001"]
"example/app/websockets.py" = ["T201"]
"example/core/configs.py" = ["ERA001"]
"example/app/urls.py" = ["F403", "F405"]
"tests/*" = ["A003"]

[format]
quote-style = "single"
