configs:
  - URLs: config.urls

  # Go To https://framework.org/Middlewares For More Options
  - Middlewares: middlewares

  # Go To https://framework.org/Authentications For More Options
  - Authentication: framework.authentication.JWTAuthentication

  # Go To https://framework.org/DatabaseDrivers For More Options
  - DatabaseDriver: framework.db.drivers.MYSQLDriver


  - LogQueries: True


