configs:
  - URLs: config.urls

  # Go To https://framework.org/Middlewares For More Options
  - Middlewares: config.middlewares

  # Go To https://framework.org/Authentications For More Options
  - Authentication: JWTAuthentication

  # Go To https://framework.org/DatabaseDrivers For More Options
  - DatabaseDriver: MYSQLDriver

  - LogQueries: True



